<?php
require __DIR__.'/layout.php';
if(!user() || user()['role']!=='admin') {header('Location: index.php?view=login');exit;}
$me=user(); page_start('admin_panel.php',t('nav_admin'));
$users=query('SELECT u.id,u.full_name,u.email,u.role,u.created_at,(SELECT COUNT(*) FROM waste_listings w WHERE w.farmer_id=u.id) AS lots FROM users u ORDER BY u.id')->get_result()->fetch_all(MYSQLI_ASSOC);
$all=query('SELECT w.*,u.full_name,u.email FROM waste_listings w JOIN users u ON u.id=w.farmer_id ORDER BY w.created_at DESC')->get_result()->fetch_all(MYSQLI_ASSOC);
$messages=(int)query('SELECT COUNT(*) AS n FROM messages')->get_result()->fetch_assoc()['n'];
$tons=array_sum(array_map(fn($l)=>(float)$l['quantity_tons'],$all));
$roleCount=array_count_values(array_column($users,'role'));
$statusCount=array_count_values(array_column($all,'status'));
$materialCount=array_count_values(array_column($all,'product_type'));
?>
<div class="page-heading"><div><div class="eyebrow"><?=esc(t('adm_eyebrow'))?></div><h1><?=esc(t('adm_title'))?></h1><p><?=esc(t('adm_lead'))?></p></div></div>
<div class="stats-strip"><div><span class="stat-icon green"><i data-lucide="users"></i></span><div><strong><?=count($users)?></strong><span><?=esc(t('adm_total_users'))?></span></div></div><div><span class="stat-icon peach"><i data-lucide="package"></i></span><div><strong><?=count($all)?></strong><span><?=esc(t('adm_total_lots'))?></span></div></div><div><span class="stat-icon lilac"><i data-lucide="package-open"></i></span><div><strong><?=number_format($tons,1)?><small> t</small></strong><span><?=esc(t('adm_total_tons'))?></span></div></div><div><span class="stat-icon blue"><i data-lucide="message-circle"></i></span><div><strong><?=$messages?></strong><span><?=esc(t('adm_total_msgs'))?></span></div></div></div>
<div class="admin-breakdown"><?php foreach([['Accounts by role',$roleCount],['Listings by status',$statusCount],['Listings by material',$materialCount]] as [$title,$set]): ?><div><b><?=esc($title)?></b><?php if(!$set): ?><p class="muted"><?=esc(t('none_yet'))?></p><?php else: foreach($set as $k=>$n): ?><div class="bar-row"><span><?=esc(ucfirst((string)$k))?></span><span class="bar"><span style="width:<?=max(4,round($n/max(1,max($set))*100))?>%"></span></span><b><?=$n?></b></div><?php endforeach; endif ?></div><?php endforeach ?></div>
<div class="section-heading mt-4"><h2><?=esc(t('adm_users'))?> <span class="count"><?=count($users)?></span></h2></div>
<div class="table-responsive"><table class="table"><thead><tr><th>#</th><th><?=esc(t('adm_owner'))?></th><th><?=esc(t('adm_role'))?></th><th><?=esc(t('sup_lots'))?></th><th><?=esc(t('adm_joined'))?></th></tr></thead><tbody><?php foreach($users as $usr): ?><tr><td class="muted"><?=(int)$usr['id']?></td><td><b><a href="profile.php?id=<?=(int)$usr['id']?>"><?=esc($usr['full_name'])?></a></b><?php if((int)$usr['id']===(int)$me['id']): ?> <span class="pilot-badge"><?=esc(t('adm_self'))?></span><?php endif ?><small class="d-block muted"><?=esc($usr['email'])?></small></td><td><?php if((int)$usr['id']===(int)$me['id']): ?><span class="muted"><?=esc(ucfirst($usr['role']))?></span><?php else: ?><select class="form-select form-select-sm admin-role" data-id="<?=(int)$usr['id']?>" aria-label="<?=esc(t('adm_set_role'))?>"><?php foreach(['farmer','business','admin'] as $r): ?><option value="<?=$r?>" <?=$usr['role']===$r?'selected':''?>><?=esc(ucfirst($r))?></option><?php endforeach ?></select><?php endif ?></td><td><?=(int)$usr['lots']?></td><td class="muted"><?=esc(substr((string)$usr['created_at'],0,10))?></td></tr><?php endforeach ?></tbody></table></div>
<div class="section-heading mt-4"><h2><?=esc(t('adm_listings'))?> <span class="count"><?=count($all)?></span></h2><div class="search-wrap"><i data-lucide="search"></i><input id="admin-search" placeholder="Search listings or owners" aria-label="Search listings"></div></div>
<?php if(!$all): ?><p class="muted"><?=esc(t('none_yet'))?></p><?php else: ?>
<div class="table-responsive"><table class="table"><thead><tr><th>#</th><th><?=esc(t('material'))?></th><th><?=esc(t('adm_owner'))?></th><th><?=esc(t('quantity'))?></th><th><?=esc(t('status'))?></th><th><?=esc(t('actions'))?></th></tr></thead><tbody id="admin-rows"><?php foreach($all as $l): ?><tr data-search="<?=esc(mb_strtolower($l['product_type'].' '.$l['full_name'].' '.$l['email'].' '.$l['description']))?>"><td class="muted"><?=(int)$l['id']?></td><td><b><?=esc($l['product_type'])?></b><small class="d-block muted"><?=esc($l['description'])?></small></td><td><a href="profile.php?id=<?=(int)$l['farmer_id']?>"><?=esc($l['full_name'])?></a></td><td><?=number_format((float)$l['quantity_tons'],3)?> t</td><td><select class="form-select form-select-sm admin-status" data-id="<?=(int)$l['id']?>" aria-label="<?=esc(t('status'))?>"><?php foreach(['available'=>t('sup_available'),'reserved'=>t('sup_reserved'),'sold'=>t('sup_sold')] as $k=>$label): ?><option value="<?=$k?>" <?=$l['status']===$k?'selected':''?>><?=esc($label)?></option><?php endforeach ?></select></td><td class="row-actions"><a class="icon-btn" title="View on map" aria-label="View on map" href="map.php?listing=<?=(int)$l['id']?>"><i data-lucide="map-pin"></i></a><button class="icon-btn danger admin-delete" data-id="<?=(int)$l['id']?>" data-label="<?=esc($l['product_type'].' — '.$l['full_name'])?>" title="<?=esc(t('sup_delete'))?>" aria-label="<?=esc(t('sup_delete'))?>"><i data-lucide="trash-2"></i></button></td></tr><?php endforeach ?></tbody></table></div>
<p id="admin-empty" hidden><?=esc(t('none_yet'))?></p>
<?php endif ?>
<p class="muted mt-4"><i data-lucide="info"></i> Account deletion is intentionally absent: users are referenced by listings, messages and subscriptions, so removal needs a retention decision rather than a button. Role changes take effect at the user's next sign-in.</p>
<?php page_end(); ?>
