<?php
require __DIR__.'/layout.php';
if(!user() || user()['role']!=='farmer') {header('Location: index.php?view=login');exit;}
$u=user(); page_start('farmer_dashboard.php',t('nav_inventory'));
$items=query('SELECT * FROM waste_listings WHERE farmer_id=? ORDER BY id DESC','i',[$u['id']])->get_result()->fetch_all(MYSQLI_ASSOC);
$by=fn(string $s)=>array_values(array_filter($items,fn($l)=>$l['status']===$s));
$available=$by('available'); $reserved=$by('reserved'); $sold=$by('sold');
$value=array_sum(array_map(fn($l)=>(float)$l['quantity_tons']*(float)$l['price_per_ton'],$available));
$tons=array_sum(array_map(fn($l)=>(float)$l['quantity_tons'],$available));
// Buyers who followed this farmer, with the suitability score recorded at follow time.
$interest=query('SELECT s.business_id,u.full_name,u.profile_data,s.created_at,(SELECT MAX(m.ai_score) FROM matches_and_ads m WHERE m.business_id=s.business_id AND m.farmer_id=s.farmer_id) AS score FROM subscriptions s JOIN users u ON u.id=s.business_id WHERE s.farmer_id=? ORDER BY s.created_at DESC','i',[$u['id']])->get_result()->fetch_all(MYSQLI_ASSOC);
$names=['Pomegranate'=>'Pomegranate peels','Walnut'=>'Walnut shells','Olive Pomace'=>'Olive pomace / jift'];
?>
<div class="page-heading"><div><div class="eyebrow"><?=esc(t('sup_eyebrow'))?></div><h1><?=esc(t('sup_title'))?></h1><p><?=esc(t('sup_lead'))?></p></div><div class="heading-actions"><a class="btn btn-light" href="voice_listing.php"><i data-lucide="mic"></i><?=esc(t('nav_quick'))?></a><button class="btn btn-green" id="new-listing"><i data-lucide="plus"></i><?=esc(t('sup_new'))?></button></div></div>
<div class="stats-strip"><div><span class="stat-icon green"><i data-lucide="package"></i></span><div><strong><?=count($items)?></strong><span><?=esc(t('sup_lots'))?></span></div></div><div><span class="stat-icon peach"><i data-lucide="package-open"></i></span><div><strong><?=number_format($tons,1)?><small> t</small></strong><span><?=esc(t('sup_available'))?></span></div></div><div><span class="stat-icon lilac"><i data-lucide="coins"></i></span><div><strong><?=number_format($value)?><small> IQD</small></strong><span><?=esc(t('sup_value'))?></span></div></div><div><span class="stat-icon blue"><i data-lucide="users"></i></span><div><strong><?=count($interest)?></strong><span><?=esc(t('sup_interest'))?></span></div></div></div>
<div class="inventory-layout"><section>
<div class="section-heading"><h2><?=esc(t('sup_inventory'))?> <span class="count"><?=count($items)?></span></h2><div class="search-wrap"><i data-lucide="search"></i><input id="lot-search" placeholder="<?=esc(t('sup_search'))?>" aria-label="<?=esc(t('sup_search'))?>"></div></div>
<div class="material-filters" role="group" aria-label="Filter by status"><button class="selected" data-lot-filter="all"><?=esc(t('all'))?> <span class="count"><?=count($items)?></span></button><button data-lot-filter="available"><?=esc(t('sup_available'))?> <span class="count"><?=count($available)?></span></button><button data-lot-filter="reserved"><?=esc(t('sup_reserved'))?> <span class="count"><?=count($reserved)?></span></button><button data-lot-filter="sold"><?=esc(t('sup_sold'))?> <span class="count"><?=count($sold)?></span></button></div>
<div class="table-responsive"><table class="table"><thead><tr><th><?=esc(t('material'))?></th><th><?=esc(t('quantity'))?></th><th><?=esc(t('price'))?></th><th><?=esc(t('status'))?></th><th><?=esc(t('actions'))?></th></tr></thead><tbody id="lot-rows">
<?php foreach($items as $l): ?><tr data-status="<?=esc($l['status'])?>" data-search="<?=esc(mb_strtolower($l['product_type'].' '.$l['description']))?>"><td><b><?=esc($names[$l['product_type']] ?? $l['product_type'])?></b><small class="d-block muted"><?=esc($l['description'])?></small></td><td><?=number_format((float)$l['quantity_tons'],3)?> t</td><td><?=number_format((float)$l['price_per_ton'])?></td><td><select class="form-select form-select-sm lot-status" data-id="<?=(int)$l['id']?>" aria-label="<?=esc(t('status'))?>"><?php foreach(['available'=>t('sup_available'),'reserved'=>t('sup_reserved'),'sold'=>t('sup_sold')] as $k=>$label): ?><option value="<?=$k?>" <?=$l['status']===$k?'selected':''?>><?=esc($label)?></option><?php endforeach ?></select></td><td class="row-actions"><button title="<?=esc(t('sup_edit'))?>" aria-label="<?=esc(t('sup_edit'))?>" class="icon-btn edit-listing" data-listing="<?=esc(json_encode($l))?>"><i data-lucide="pencil"></i></button><button title="<?=esc(t('sup_delete'))?>" aria-label="<?=esc(t('sup_delete'))?>" class="icon-btn danger lot-delete" data-id="<?=(int)$l['id']?>" data-label="<?=esc($names[$l['product_type']] ?? $l['product_type'])?>"><i data-lucide="trash-2"></i></button></td></tr><?php endforeach ?>
</tbody></table></div><p id="lot-empty" <?=$items?'hidden':''?>><?=esc(t('none_yet'))?></p>
<div class="section-heading mt-4"><h2><?=esc(t('sup_buyers'))?> <span class="count"><?=count($interest)?></span></h2></div>
<?php if(!$interest): ?><p class="muted"><?=esc(t('sup_no_buyers'))?></p><?php else: ?>
<div class="table-responsive"><table class="table"><thead><tr><th><?=esc(t('buyer'))?></th><th><?=esc(t('sup_score'))?></th><th><?=esc(t('adm_joined'))?></th><th></th></tr></thead><tbody><?php foreach($interest as $b): $p=json_decode($b['profile_data'] ?? '{}',true) ?: []; ?><tr><td><b><a href="profile.php?id=<?=(int)$b['business_id']?>"><?=esc($b['full_name'])?></a></b><small class="d-block muted"><?=esc($p['industry'] ?? '—')?><?= isset($p['product'])?' · wants '.esc($p['product']):'' ?></small></td><td><?= $b['score']!==null?'<b>'.round((float)$b['score']).'%</b>':'<span class="muted">—</span>' ?></td><td class="muted"><?=esc(substr((string)$b['created_at'],0,10))?></td><td><a class="btn btn-sm btn-light" href="chat.php?receiver=<?=(int)$b['business_id']?>"><i data-lucide="message-circle"></i>Message</a></td></tr><?php endforeach ?></tbody></table></div>
<?php endif ?>
</section>
<section class="inventory-editor"><h2 id="editor-title"><?=esc(t('sup_add'))?></h2><form id="listing-form"><input type="hidden" name="action" value="save_listing"><input type="hidden" name="id" value="0"><label><?=esc(t('material'))?><select class="form-select" name="product_type"><option>Pomegranate</option><option>Walnut</option><option>Olive Pomace</option></select></label><div class="form-pair"><label><?=esc(t('quantity'))?><input class="form-control" name="quantity_tons" type="number" min="0.001" step="0.001" required></label><label><?=esc(t('price'))?><input class="form-control" name="price_per_ton" type="number" min="0" step="0.01" value="0" required></label></div><div class="form-pair"><label><?=esc(t('latitude'))?><input class="form-control" name="location_lat" type="number" min="-90" max="90" step="any" value="35.56" required></label><label><?=esc(t('longitude'))?><input class="form-control" name="location_lng" type="number" min="-180" max="180" step="any" value="45.43" required></label></div><button type="button" id="locate" class="btn btn-light btn-sm"><i data-lucide="locate-fixed"></i><?=esc(t('sup_locate'))?></button><label><?=esc(t('notes'))?><textarea class="form-control" name="description" rows="3" maxlength="4000"></textarea></label><label><?=esc(t('status'))?><select class="form-select" name="status"><option value="available"><?=esc(t('sup_available'))?></option><option value="reserved"><?=esc(t('sup_reserved'))?></option><option value="sold"><?=esc(t('sup_sold'))?></option></select></label><button class="btn btn-green w-100"><i data-lucide="check"></i><?=esc(t('sup_save'))?></button></form></section></div>
<template id="photo-field"><label><?=esc(t('sup_photo'))?><input class="form-control" type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label></template>
<?php page_end(); ?>
