<?php require __DIR__.'/layout.php'; page_start('index.php','Marketplace');
try {$items=listings();} catch(Throwable $e) {$items=[]; echo '<div class="alert alert-warning">Database needs setup. See README.md, then refresh.</div>';}
if(($_GET['view'] ?? '')==='login'): ?>
<div class="page-heading"><div><div class="eyebrow">WELCOME TO ECOZÎN</div><h1>Connect to a circular future.</h1><p>Join the local network of farmers and material buyers.</p></div></div>
<?php if(isset($_SESSION['flash'])): ?><div class="alert alert-warning"><?=esc($_SESSION['flash'])?></div><?php unset($_SESSION['flash']); endif ?>
<div class="auth-grid"><section><h2>Sign in</h2><form action="auth.php" method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="action" value="login"><label>Email<input class="form-control" type="email" name="email" required autocomplete="email"></label><label>Password<input class="form-control" type="password" name="password" required autocomplete="current-password"></label><button class="btn btn-green">Sign in <i data-lucide="arrow-right"></i></button></form><div class="demo-accounts"><b>Demo accounts</b><p>buyer@ecozin.test<br>farmer@ecozin.test</p><small>Password: EcozinDemo2026!</small></div></section><section><h2>Create an account</h2><form action="auth.php" method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="action" value="register"><label>Full name<input class="form-control" name="full_name" maxlength="120" required></label><label>Email<input class="form-control" type="email" name="email" required></label><label>Password<input class="form-control" type="password" name="password" minlength="10" required></label><label>Account type<select class="form-select" name="role"><option value="business">Business / material buyer</option><option value="farmer">Farmer / material supplier</option></select></label><label>Industry<input class="form-control" name="industry" placeholder="e.g. organic cosmetics"></label><label>Preferred material<select class="form-select" name="product"><option>Pomegranate</option><option>Walnut</option><option>Olive Pomace</option></select></label><button class="btn btn-green">Create account</button></form></section></div>
<?php else: $available=array_values(array_filter($items,fn($l)=>$l['status']==='available')); $tons=array_sum(array_column($available,'quantity_tons')); ?>
<div class="page-heading"><div><div class="eyebrow">LOCAL MATERIALS. NEW POSSIBILITIES.</div><h1>Waste becomes opportunity<span>.</span></h1><p>Discover agricultural byproducts ready for their next life.</p></div><a class="btn btn-green" href="farmer_dashboard.php"><i data-lucide="plus"></i> List your material</a></div>
<div class="stats-strip"><div><span class="stat-icon green"><i data-lucide="package-open"></i></span><div><strong><?=number_format($tons,1)?><small> tons</small></strong><span>Available for recovery</span></div></div><div><span class="stat-icon peach"><i data-lucide="users"></i></span><div><strong><?=count(array_unique(array_column($items,'farmer_id')))?></strong><span>Farmers in the network</span></div></div><div><span class="stat-icon lilac"><i data-lucide="layers"></i></span><div><strong>3</strong><span>Material streams</span></div></div><div><span class="stat-icon blue"><i data-lucide="map-pin"></i></span><div><strong>Slemani</strong><span>Rooted in our region</span></div></div></div>
<section class="feature-band"><div><span class="eyebrow">A BETTER SECOND LIFE</span><h2>From the harvest.<br>Back into the economy.</h2><p>Peels, shells and pomace. Local resources<br>for the businesses building what comes next.</p><a href="ai_knowledge_base.php">Explore material potential <i data-lucide="arrow-right"></i></a></div><img src="assets/pomegranate.jpg" alt="Pomegranate fruit and peel"></section>
<div class="section-heading"><h2>Available materials <span class="count"><?=count($available)?></span></h2><div class="muted"><span class="live-dot"></span> Direct from local farmers</div></div><div class="filter-bar"><div class="material-filters" role="group" aria-label="Filter materials"><button class="selected" data-filter="all">All materials</button><button data-filter="Pomegranate">Pomegranate</button><button data-filter="Walnut">Walnut</button><button data-filter="Olive Pomace">Olive pomace</button></div><div class="search-wrap"><i data-lucide="search"></i><input id="search" placeholder="Search materials or farmers" aria-label="Search listings"></div></div>
<div class="listing-grid" id="marketplace"><?php foreach($available as $l): ?><div class="listing-wrapper" data-product="<?=esc($l['product_type'])?>" data-search="<?=esc(strtolower($l['product_type'].' '.$l['full_name'].' '.$l['description']))?>"><?php listing_card($l); ?></div><?php endforeach ?></div><p id="empty-search" hidden>No materials match your search.</p>
<?php endif; page_end(); ?>
