<?php
// Offline reference briefs. These are starting points, not tested material specifications.
return [
 'English'=>[
  'Pomegranate'=>"POMEGRANATE PEELS\n\nPotential applications\nPeels contain tannins and other polyphenols. Potential buyers include natural dye makers, research laboratories and processors developing botanical extracts. Cosmetic applications require extraction, safety assessment and quality testing.\n\nPreparation\nSeparate peels from mixed waste, dry promptly in clean conditions and store away from moisture. Record origin, harvest date, drying method and batch weight.\n\nQuality checks\nAsk buyers for moisture, contamination, particle size and traceability requirements. Do not claim antioxidant concentration without laboratory analysis.\n\nNext step\nShare a representative sample and agree on specifications before committing a batch.",
  'Walnut'=>"WALNUT SHELLS\n\nPotential applications\nClean hard shells may be suitable for abrasive media, filtration research, fillers or biomass processing. Green husks and hard shells are different materials and should be listed separately in the description.\n\nPreparation\nRemove kernels and debris. Dry, grade and crush only to the buyer's requested size.\n\nQuality checks\nCheck moisture, foreign matter, particle distribution and residual oils. Dust control and appropriate protective equipment are needed during processing.\n\nNext step\nProvide a sample and particle-size specification. Industrial suitability requires buyer testing.",
  'Olive Pomace'=>"OLIVE POMACE / JIFT\n\nPotential applications\nOlive milling residue can be considered by biomass fuel processors and composting operators. Suitability depends on moisture, residual oil, ash and contamination.\n\nPreparation\nRecord milling method, storage duration and moisture conditions. Avoid uncontrolled dumping and wet piles. Drying and fuel processing need suitable equipment.\n\nQuality checks\nRequest laboratory analysis for heating value and ash rather than estimating these from appearance. Composting requires controlled processing; untreated material is not automatically suitable for direct field application.\n\nNext step\nSend a sample to the buyer and agree on drying, transport and acceptance criteria."
 ],
 'Arabic'=>[
  'Pomegranate'=>"قشور الرمان\n\nتحتوي على مركبات نباتية وتانينات. من المشترين المحتملين منتجو الأصباغ الطبيعية ومختبرات البحث ومصانع المستخلصات. تتطلب الاستخدامات التجميلية اختبارات جودة وسلامة.\n\nافصل القشور عن النفايات المختلطة وجففها في ظروف نظيفة واحفظها بعيداً عن الرطوبة. سجل المصدر وتاريخ الحصاد وطريقة التجفيف والوزن.\n\nاتفق مع المشتري على الرطوبة والشوائب وحجم الجزيئات. لا تدّعِ تركيزاً محدداً دون تحليل مختبري. أرسل عينة قبل الاتفاق على شراء الكمية.",
  'Walnut'=>"قشور الجوز\n\nقد تستخدم القشور الصلبة النظيفة في مواد الصقل والحشوات أو معالجة الكتلة الحيوية. القشرة الخضراء مختلفة عن القشرة الصلبة؛ وضح نوع المادة في الإعلان.\n\nأزل بقايا اللب والشوائب وجفف القشور وفرزها بحسب طلب المشتري. راقب الرطوبة وحجم الجزيئات والزيوت المتبقية. يحتاج الطحن إلى التحكم بالغبار ومعدات حماية.\n\nأرسل عينة للمشتري واتفق على مواصفات القبول قبل البيع.",
  'Olive Pomace'=>"تفل الزيتون / الجفت\n\nقد يناسب مصانع وقود الكتلة الحيوية أو مرافق التسميد بعد المعالجة. تعتمد الملاءمة على الرطوبة والزيت المتبقي والرماد والشوائب.\n\nسجل طريقة العصر وظروف التخزين. تجنب التكديس الرطب والتخلص العشوائي. يتطلب التجفيف معدات مناسبة.\n\nاطلب تحليل القيمة الحرارية والرماد ولا تستنتجهما من المظهر. لا تفترض أن المادة الخام مناسبة للاستخدام المباشر في الحقل. أرسل عينة واتفق على النقل والتجفيف وشروط القبول."
 ],
 'Kurdish Sorani'=>[
  'Pomegranate'=>"توێکڵی هەنار\n\nتوێکڵەکان تانین و ماددەی ڕووەکییان تێدایە. بەرهەمهێنەرانی ڕەنگی سروشتی و تاقیگەکان و کارگەکانی دەرهێنانی ماددە دەکرێت کڕیار بن. بەکارهێنانی جوانکاری پێویستی بە پشکنینی کوالێتی و سەلامەتی هەیە.\n\nتوێکڵەکان لە پاشماوەی تێکەڵ جیا بکەرەوە، بە پاکی وشکیان بکەرەوە و لە شێ دوریان بخەرەوە. سەرچاوە و بەرواری دروێنە و کێش تۆمار بکە.\n\nلەگەڵ کڕیار لەسەر شێ و پیسی و قەبارەی وردەکان ڕێک بکەوە. بەبێ پشکنینی تاقیگە بانگەشەی ڕێژەی ماددەکان مەکە. پێش فرۆشتن نموونە بنێرە.",
  'Walnut'=>"توێکڵی گوێز\n\nتوێکڵە ڕەقە پاکەکان دەکرێت بۆ ماددەی سڕینەوە و پڕکەرەوە یان پرۆسەی سووتەمەنی بەکار بهێنرێن. توێکڵی سەوز و توێکڵی ڕەق جیاوازن؛ جۆری ماددەکە ڕوون بکەرەوە.\n\nناوک و پیسی لێ جیا بکەرەوە. بەپێی داواکاری کڕیار وشک و پۆلێنی بکە. شێ و قەبارە و ڕۆنی ماوە پشکنین بکە. وردکردنەوە پێویستی بە کۆنترۆڵی تۆز و پاراستن هەیە.\n\nنموونە بنێرە و پێش فرۆشتن لەسەر مەرجەکانی وەرگرتن ڕێک بکەوە.",
  'Olive Pomace'=>"پاشماوەی زەیتوون / جفت\n\nدەکرێت دوای چارەسەرکردن بۆ سووتەمەنی زیندەیی یان کۆمپۆست بەکار بهێنرێت. گونجاوی بە شێ و ڕۆنی ماوە و خۆڵەمێش و پیسیەوە بەستراوە.\n\nشێوازی گوشین و ماوەی هەڵگرتن تۆمار بکە. کۆکردنەوەی تەڕ و فڕێدانی هەڕەمەکی مەکە. وشککردنەوە ئامێری گونجاوی دەوێت.\n\nبۆ وزەی گەرمی و خۆڵەمێش پشکنینی تاقیگە داوا بکە. ماددەی خام بەبێ چارەسەرکردن بۆ کێڵگە بە گونجاو مەزانە. نموونە بنێرە و لەسەر گواستنەوە و مەرجی وەرگرتن ڕێک بکەوە."
 ]
];
