<?php
// UI strings. PHASE 1 covers navigation plus the two new farmer-facing pages; the older pages are
// still English-only and get converted in a later phase. Missing keys fall back to English, then to
// the key itself, so adding a key here never breaks a page.
// Sorani and Arabic strings need review by a qualified speaker before a public launch.
return [
 'en'=>[
  'nav_market'=>'Marketplace','nav_matches'=>'Smart matches','nav_inventory'=>'My inventory','nav_quick'=>'Quick list',
  'nav_pool'=>'Combine lots','nav_map'=>'Pickup map','nav_chat'=>'Messages','nav_knowledge'=>'Material intelligence',
  'signin'=>'Sign in / Join','signout'=>'Sign out','workspace'=>'Workspace','account'=>'account',
  'quick_eyebrow'=>'SPEAK OR TYPE — NO FORMS','quick_title'=>'Just tell us what you have.',
  'quick_lead'=>'Describe your material in your own words. We fill in the listing for you to check.',
  'quick_placeholder'=>'Example: I have about 3 tons of dried pomegranate peels in Said Sadiq, sorted and ready next week.',
  'quick_read'=>'Read my description','quick_speak'=>'Speak instead','quick_listening'=>'Listening… speak now.',
  'quick_review'=>'Check these details','quick_review_hint'=>'We filled these in from your description. Correct anything that is wrong, then save.',
  'quick_confirm'=>'Save my listing','quick_missing'=>'We could not read everything. Please complete the highlighted fields.',
  'material'=>'Material','quantity'=>'Quantity (tons)','price'=>'Price / ton (IQD)','location'=>'Location',
  'latitude'=>'Latitude','longitude'=>'Longitude','notes'=>'Preparation / quality','status'=>'Status',
  'pool_eyebrow'=>'ONE TRUCK. SEVERAL FARMS.','pool_title'=>'Combine small lots into one pickup.',
  'pool_lead'=>'No single farm has twenty tons. Together they do. Pool nearby lots of the same material into one collection run.',
  'pool_target'=>'Tonnage you need','pool_radius'=>'Search radius (km)','pool_build'=>'Build a combined lot',
  'pool_total'=>'Pooled volume','pool_farms'=>'Farms involved','pool_point'=>'Suggested collection point',
  'pool_route'=>'Plan collection route','pool_none'=>'No lots of this material are available within that radius yet.',
  'pool_short'=>'Available lots do not reach your target yet. Here is everything within range.',
  'burn_title'=>'If this is burned instead','burn_revenue'=>'Income the farmer loses',
  'burn_soil'=>'A 2025 study of wheat residue burning in Wazha village and Sitak, Sulaymaniyah measured soil organic matter falling about 25% and magnesium falling about two thirds.',
 ],
 'ckb'=>[
  'nav_market'=>'بازاڕ','nav_matches'=>'پێشنیاری زیرەک','nav_inventory'=>'کاڵای من','nav_quick'=>'تۆمارکردنی خێرا',
  'nav_pool'=>'کۆکردنەوەی بەرهەم','nav_map'=>'نەخشەی وەرگرتن','nav_chat'=>'نامەکان','nav_knowledge'=>'زانیاری ماددە',
  'signin'=>'چوونەژوورەوە / بەشداری','signout'=>'چوونەدەرەوە','workspace'=>'شوێنی کار','account'=>'هەژمار',
  'quick_eyebrow'=>'بدوێ یان بنووسە — بەبێ فۆرم','quick_title'=>'تەنها پێمان بڵێ چیت هەیە.',
  'quick_lead'=>'بە وشەی خۆت باسی ماددەکەت بکە. ئێمە تۆمارەکە بۆت پڕ دەکەینەوە بۆ پشکنین.',
  'quick_placeholder'=>'نموونە: نزیکەی سێ تۆن توێکڵی هەناری وشک لە سەیدسادق هەیە، جیاکراوە و هەفتەی داهاتوو ئامادەیە.',
  'quick_read'=>'وەسفەکەم بخوێنە','quick_speak'=>'لە جیاتی ئەوە بدوێ','quick_listening'=>'گوێ دەگرم… ئێستا بدوێ.',
  'quick_review'=>'ئەم وردەکارییەکان پشکنین بکە','quick_review_hint'=>'ئەمانە لە وەسفەکەت پڕکراونەتەوە. هەر هەڵەیەک ڕاست بکەوە، پاشان پاشەکەوت بکە.',
  'quick_confirm'=>'تۆمارەکەم پاشەکەوت بکە','quick_missing'=>'نەتوانرا هەموو شتێک بخوێنرێت. تکایە خانەکانی نیشانکراو تەواو بکە.',
  'material'=>'ماددە','quantity'=>'بڕ (تۆن)','price'=>'نرخ / تۆن (دینار)','location'=>'شوێن',
  'latitude'=>'پانی','longitude'=>'درێژی','notes'=>'ئامادەکاری / کوالیتی','status'=>'بارودۆخ',
  'pool_eyebrow'=>'یەک بارهەڵگر. چەند کێڵگە.','pool_title'=>'بڕی بچووک بکە یەک وەرگرتن.',
  'pool_lead'=>'هیچ کێڵگەیەک بە تەنها بیست تۆنی نییە. پێکەوە هەیانە. بڕەکانی نزیکی هەمان ماددە کۆبکەوە.',
  'pool_target'=>'ئەو بڕە کە پێویستت پێیەتی','pool_radius'=>'تیرەی گەڕان (کم)','pool_build'=>'بڕێکی کۆکراوە دروست بکە',
  'pool_total'=>'بڕی کۆکراوە','pool_farms'=>'کێڵگەی بەشدار','pool_point'=>'شوێنی پێشنیارکراوی کۆکردنەوە',
  'pool_route'=>'ڕێگەی کۆکردنەوە پلان بکە','pool_none'=>'هێشتا هیچ بڕێکی ئەم ماددەیە لەم تیرەیەدا بەردەست نییە.',
  'pool_short'=>'بڕەکانی بەردەست هێشتا نەگەیشتوونە ئامانجەکەت. ئەمە هەموو ئەوەیە کە لە مەودادایە.',
  'burn_title'=>'ئەگەر لە جیاتی ئەوە بسووتێنرێت','burn_revenue'=>'ئەو داهاتە کە جوتیار لە دەستی دەدات',
  'burn_soil'=>'لێکۆڵینەوەیەکی ٢٠٢٥ لەسەر سووتاندنی پاشماوەی گەنم لە گوندی وەژە و سیتەک، سلێمانی، پیشانی دا کە ماددەی ئۆرگانیکی خاک نزیکەی ٢٥٪ و ماگنیسیۆم نزیکەی دوو لەسەر سێ کەم دەبێتەوە.',
 ],
 'ar'=>[
  'nav_market'=>'السوق','nav_matches'=>'المطابقات الذكية','nav_inventory'=>'مخزوني','nav_quick'=>'إدراج سريع',
  'nav_pool'=>'تجميع الكميات','nav_map'=>'خريطة الاستلام','nav_chat'=>'الرسائل','nav_knowledge'=>'معلومات المواد',
  'signin'=>'تسجيل الدخول / انضم','signout'=>'تسجيل الخروج','workspace'=>'مساحة العمل','account'=>'حساب',
  'quick_eyebrow'=>'تحدث أو اكتب — بدون نماذج','quick_title'=>'فقط أخبرنا بما لديك.',
  'quick_lead'=>'اوصف مادتك بكلماتك. سنعبئ الإدراج لتتحقق منه.',
  'quick_placeholder'=>'مثال: لدي حوالي ٣ أطنان من قشور الرمان المجففة في سيد صادق، مفروزة وجاهزة الأسبوع القادم.',
  'quick_read'=>'اقرأ وصفي','quick_speak'=>'تحدث بدلاً من ذلك','quick_listening'=>'أستمع… تحدث الآن.',
  'quick_review'=>'تحقق من هذه التفاصيل','quick_review_hint'=>'عبأناها من وصفك. صحح أي خطأ ثم احفظ.',
  'quick_confirm'=>'احفظ الإدراج','quick_missing'=>'لم نتمكن من قراءة كل شيء. أكمل الحقول المحددة.',
  'material'=>'المادة','quantity'=>'الكمية (طن)','price'=>'السعر / طن (دينار)','location'=>'الموقع',
  'latitude'=>'خط العرض','longitude'=>'خط الطول','notes'=>'التحضير / الجودة','status'=>'الحالة',
  'pool_eyebrow'=>'شاحنة واحدة. عدة مزارع.','pool_title'=>'اجمع الكميات الصغيرة في عملية استلام واحدة.',
  'pool_lead'=>'لا مزرعة واحدة تملك عشرين طناً. معاً تملكها. اجمع الكميات القريبة من نفس المادة.',
  'pool_target'=>'الكمية المطلوبة','pool_radius'=>'نطاق البحث (كم)','pool_build'=>'أنشئ كمية مجمعة',
  'pool_total'=>'الحجم المجمع','pool_farms'=>'المزارع المشاركة','pool_point'=>'نقطة الجمع المقترحة',
  'pool_route'=>'خطط مسار الجمع','pool_none'=>'لا توجد كميات من هذه المادة في هذا النطاق بعد.',
  'pool_short'=>'الكميات المتاحة لم تبلغ هدفك بعد. هذا كل ما هو في النطاق.',
  'burn_title'=>'إذا تم حرقها بدلاً من ذلك','burn_revenue'=>'الدخل الذي يخسره المزارع',
  'burn_soil'=>'قاست دراسة من عام ٢٠٢٥ لحرق مخلفات الحنطة في قرية وەژە وسيتك، السليمانية، انخفاض المادة العضوية في التربة بنحو ٢٥٪ والمغنيسيوم بنحو الثلثين.',
 ],
];
