<?php
// UI strings. Navigation, the quick-list page, the lot-pooling page and the three role consoles are
// translated; the remaining older pages are still English-only and get converted in a later phase.
// Missing keys fall back to English, then to the key itself, so adding a key never breaks a page.
// Sorani and Arabic strings need review by a qualified speaker before a public launch.
return [
 'en'=>[
  'nav_market'=>'Marketplace','nav_matches'=>'Smart matches','nav_inventory'=>'My inventory','nav_quick'=>'Quick list',
  'nav_pool'=>'Combine lots','nav_map'=>'Pickup map','nav_chat'=>'Messages','nav_knowledge'=>'Material intelligence','nav_admin'=>'Administration',
  'signin'=>'Sign in / Join','signout'=>'Sign out','workspace'=>'Workspace','account'=>'account',
  'quick_eyebrow'=>'SPEAK OR TYPE — NO FORMS','quick_title'=>'Just tell us what you have.',
  'quick_lead'=>'Describe your material in your own words. We fill in the listing for you to check.',
  'quick_placeholder'=>'Example: I have about 3 tons of dried pomegranate peels in Said Sadiq, sorted and ready next week.',
  'quick_read'=>'Read my description','quick_speak'=>'Speak instead','quick_listening'=>'Listening… speak now.',
  'quick_review'=>'Check these details','quick_review_hint'=>'We filled these in from your description. Correct anything that is wrong, then save.',
  'quick_confirm'=>'Save my listing','quick_missing'=>'We could not read everything. Please complete the highlighted fields.',
  'material'=>'Material','quantity'=>'Quantity (tons)','price'=>'Price / ton (IQD)','location'=>'Location',
  'latitude'=>'Latitude','longitude'=>'Longitude','notes'=>'Preparation / quality','status'=>'Status',
  'actions'=>'Actions','farmer'=>'Farmer','buyer'=>'Buyer','all'=>'All','none_yet'=>'Nothing here yet.',
  'pool_eyebrow'=>'ONE TRUCK. SEVERAL FARMS.','pool_title'=>'Combine small lots into one pickup.',
  'pool_lead'=>'No single farm has twenty tons. Together they do. Pool nearby lots of the same material into one collection run.',
  'pool_target'=>'Tonnage you need','pool_radius'=>'Search radius (km)','pool_build'=>'Build a combined lot',
  'pool_total'=>'Pooled volume','pool_farms'=>'Farms involved','pool_point'=>'Suggested collection point',
  'pool_route'=>'Plan collection route','pool_none'=>'No lots of this material are available within that radius yet.',
  'pool_short'=>'Available lots do not reach your target yet. Here is everything within range.',
  'burn_title'=>'If this is burned instead','burn_revenue'=>'Income the farmer loses',
  'burn_soil'=>'A 2025 study of wheat residue burning in Wazha village and Sitak, Sulaymaniyah measured soil organic matter falling about 25% and magnesium falling about two thirds.',
  'sup_eyebrow'=>'SUPPLIER WORKSPACE','sup_title'=>'Your harvest has more to give.',
  'sup_lead'=>'Manage every lot, keep availability current and see which buyers are asking.',
  'sup_lots'=>'Listed lots','sup_available'=>'Available now','sup_reserved'=>'Reserved','sup_sold'=>'Sold',
  'sup_value'=>'Inventory value','sup_interest'=>'Interested buyers','sup_inventory'=>'Material inventory',
  'sup_add'=>'Add material','sup_edit'=>'Edit material','sup_new'=>'New listing','sup_save'=>'Save inventory',
  'sup_delete'=>'Remove listing','sup_buyers'=>'Buyers who followed you','sup_no_buyers'=>'No buyer has followed you yet. Keep your lots marked available.',
  'sup_score'=>'Suitability','sup_search'=>'Search your lots','sup_locate'=>'Use my location','sup_photo'=>'Inventory photo',
  'buy_eyebrow'=>'BUYER WORKSPACE','buy_title'=>'Local resources. Better matches.',
  'buy_lead'=>'Your ranked shortlist, the farmers you follow, and a procurement brief.',
  'buy_matched'=>'Matched lots','buy_reachable'=>'Tons within reach','buy_following'=>'Farmers followed',
  'buy_avg'=>'Average suitability','buy_shortlist'=>'Your material shortlist','buy_follow_list'=>'Farmers you follow',
  'buy_unfollow'=>'Remove from shortlist','buy_no_following'=>'You are not following any farmer yet. Follow one from your shortlist.',
  'buy_brief'=>'Procurement brief','buy_generate'=>'Generate AI brief','buy_open_pool'=>'Combine lots into one pickup',
  'adm_eyebrow'=>'ADMINISTRATION','adm_title'=>'Platform oversight.',
  'adm_lead'=>'Accounts, listing moderation and platform totals. Actions here are logged to nothing — this is a pilot console.',
  'adm_users'=>'Accounts','adm_listings'=>'All listings','adm_role'=>'Role','adm_joined'=>'Joined',
  'adm_total_users'=>'Accounts','adm_total_lots'=>'Listings','adm_total_tons'=>'Tons listed','adm_total_msgs'=>'Messages',
  'adm_moderate'=>'Moderate','adm_set_role'=>'Change role','adm_owner'=>'Owner','adm_self'=>'You',
  'prof_title'=>'My profile','prof_eyebrow'=>'YOUR ACCOUNT','prof_public'=>'MEMBER PROFILE',
  'prof_details'=>'Profile details','prof_name'=>'Full name','prof_email'=>'Email',
  'prof_email_fixed'=>'Email is your sign-in and cannot be changed here.',
  'prof_industry'=>'Industry','prof_farm_type'=>'Farm type','prof_preferred'=>'Preferred material',
  'prof_main_material'=>'Main material','prof_preferred_hint'=>'Your shortlist scores this material 65 points instead of 15.',
  'prof_district'=>'District','prof_district_pick'=>'Pick a district to fill coordinates…',
  'prof_coord_buyer'=>'These coordinates are your facility. Proximity scoring and collection routes measure from here.',
  'prof_coord_farmer'=>'These coordinates are your default pickup point for new listings.',
  'prof_save'=>'Save profile','prof_password'=>'Password','prof_current'=>'Current password',
  'prof_new'=>'New password','prof_new_hint'=>'At least 10 characters.','prof_change'=>'Change password',
  'prof_account'=>'Account','prof_role_fixed'=>'Only an administrator can change your role.',
  'prof_message'=>'Send a message','prof_view_public'=>'View public profile','prof_region'=>'Region',
  'prof_my_lots'=>'My available lots','prof_their_lots'=>'Available lots','prof_no_lots'=>'No lots are available right now.',
  'prof_missing'=>'That profile does not exist.','nav_profile'=>'My profile',
 ],
 'ckb'=>[
  'nav_market'=>'بازاڕ','nav_matches'=>'پێشنیاری زیرەک','nav_inventory'=>'کاڵای من','nav_quick'=>'تۆمارکردنی خێرا',
  'nav_pool'=>'کۆکردنەوەی بەرهەم','nav_map'=>'نەخشەی وەرگرتن','nav_chat'=>'نامەکان','nav_knowledge'=>'زانیاری ماددە','nav_admin'=>'بەڕێوەبردن',
  'signin'=>'چوونەژوورەوە / بەشداری','signout'=>'چوونەدەرەوە','workspace'=>'شوێنی کار','account'=>'هەژمار',
  'quick_eyebrow'=>'بدوێ یان بنووسە — بەبێ فۆرم','quick_title'=>'تەنها پێمان بڵێ چیت هەیە.',
  'quick_lead'=>'بە وشەی خۆت باسی ماددەکەت بکە. ئێمە تۆمارەکە بۆت پڕ دەکەینەوە بۆ پشکنین.',
  'quick_placeholder'=>'نموونە: نزیکەی سێ تۆن توێکڵی هەناری وشک لە سەیدسادق هەیە، جیاکراوە و هەفتەی داهاتوو ئامادەیە.',
  'quick_read'=>'وەسفەکەم بخوێنە','quick_speak'=>'لە جیاتی ئەوە بدوێ','quick_listening'=>'گوێ دەگرم… ئێستا بدوێ.',
  'quick_review'=>'ئەم وردەکارییەکان پشکنین بکە','quick_review_hint'=>'ئەمانە لە وەسفەکەت پڕکراونەتەوە. هەر هەڵەیەک ڕاست بکەوە، پاشان پاشەکەوت بکە.',
  'quick_confirm'=>'تۆمارەکەم پاشەکەوت بکە','quick_missing'=>'نەتوانرا هەموو شتێک بخوێنرێت. تکایە خانەکانی نیشانکراو تەواو بکە.',
  'material'=>'ماددە','quantity'=>'بڕ (تۆن)','price'=>'نرخ / تۆن (دینار)','location'=>'شوێن',
  'latitude'=>'پانی','longitude'=>'درێژی','notes'=>'ئامادەکاری / کوالیتی','status'=>'بارودۆخ',
  'actions'=>'کردارەکان','farmer'=>'جوتیار','buyer'=>'کڕیار','all'=>'هەموو','none_yet'=>'هێشتا هیچ شتێک لێرە نییە.',
  'pool_eyebrow'=>'یەک بارهەڵگر. چەند کێڵگە.','pool_title'=>'بڕی بچووک بکە یەک وەرگرتن.',
  'pool_lead'=>'هیچ کێڵگەیەک بە تەنها بیست تۆنی نییە. پێکەوە هەیانە. بڕەکانی نزیکی هەمان ماددە کۆبکەوە.',
  'pool_target'=>'ئەو بڕە کە پێویستت پێیەتی','pool_radius'=>'تیرەی گەڕان (کم)','pool_build'=>'بڕێکی کۆکراوە دروست بکە',
  'pool_total'=>'بڕی کۆکراوە','pool_farms'=>'کێڵگەی بەشدار','pool_point'=>'شوێنی پێشنیارکراوی کۆکردنەوە',
  'pool_route'=>'ڕێگەی کۆکردنەوە پلان بکە','pool_none'=>'هێشتا هیچ بڕێکی ئەم ماددەیە لەم تیرەیەدا بەردەست نییە.',
  'pool_short'=>'بڕەکانی بەردەست هێشتا نەگەیشتوونە ئامانجەکەت. ئەمە هەموو ئەوەیە کە لە مەودادایە.',
  'burn_title'=>'ئەگەر لە جیاتی ئەوە بسووتێنرێت','burn_revenue'=>'ئەو داهاتە کە جوتیار لە دەستی دەدات',
  'burn_soil'=>'لێکۆڵینەوەیەکی ٢٠٢٥ لەسەر سووتاندنی پاشماوەی گەنم لە گوندی وەژە و سیتەک، سلێمانی، پیشانی دا کە ماددەی ئۆرگانیکی خاک نزیکەی ٢٥٪ و ماگنیسیۆم نزیکەی دوو لەسەر سێ کەم دەبێتەوە.',
  'sup_eyebrow'=>'شوێنی کاری دابینکەر','sup_title'=>'بەرهەمەکەت زیاتر دەتوانێت ببەخشێت.',
  'sup_lead'=>'هەموو بڕەکان بەڕێوە ببە، بەردەستی نوێ بکەوە و ببینە کام کڕیار داوای دەکات.',
  'sup_lots'=>'بڕەکانی تۆمارکراو','sup_available'=>'ئێستا بەردەست','sup_reserved'=>'گیراو','sup_sold'=>'فرۆشراو',
  'sup_value'=>'بەهای کاڵا','sup_interest'=>'کڕیاری خواستکار','sup_inventory'=>'کاڵای ماددە',
  'sup_add'=>'ماددە زیاد بکە','sup_edit'=>'ماددە دەستکاری بکە','sup_new'=>'تۆماری نوێ','sup_save'=>'کاڵا پاشەکەوت بکە',
  'sup_delete'=>'تۆمار لابە','sup_buyers'=>'کڕیارانێک کە شوێنت کەوتوون','sup_no_buyers'=>'هێشتا هیچ کڕیارێک شوێنت نەکەوتووە. بڕەکانت بە بەردەست دیاری بکە.',
  'sup_score'=>'گونجاوی','sup_search'=>'بڕەکانت بگەڕێ','sup_locate'=>'شوێنی من بەکاربهێنە','sup_photo'=>'وێنەی کاڵا',
  'buy_eyebrow'=>'شوێنی کاری کڕیار','buy_title'=>'سەرچاوەی ناوخۆیی. گونجاوی باشتر.',
  'buy_lead'=>'لیستی ڕیزبەندیکراوت، ئەو جوتیارانە کە شوێنیان دەکەویت، و ڕاپۆرتی کڕین.',
  'buy_matched'=>'بڕی گونجاو','buy_reachable'=>'تۆن لە دەسترا','buy_following'=>'جوتیاری شوێنکەوتوو',
  'buy_avg'=>'ناوەندی گونجاوی','buy_shortlist'=>'لیستی ماددەکانت','buy_follow_list'=>'ئەو جوتیارانە کە شوێنیان دەکەویت',
  'buy_unfollow'=>'لە لیست لابە','buy_no_following'=>'هێشتا شوێنی هیچ جوتیارێک نەکەوتووی. لە لیستەکەت یەکێک هەڵبژێرە.',
  'buy_brief'=>'ڕاپۆرتی کڕین','buy_generate'=>'ڕاپۆرتی AI دروست بکە','buy_open_pool'=>'بڕەکان بکە یەک وەرگرتن',
  'adm_eyebrow'=>'بەڕێوەبردن','adm_title'=>'چاودێری پلاتفۆرم.',
  'adm_lead'=>'هەژمارەکان، چاودێری تۆمارەکان و کۆی گشتی. ئەمە کۆنسۆلی تاقیکارییە.',
  'adm_users'=>'هەژمارەکان','adm_listings'=>'هەموو تۆمارەکان','adm_role'=>'ڕۆڵ','adm_joined'=>'بەشداری کردووە',
  'adm_total_users'=>'هەژمار','adm_total_lots'=>'تۆمار','adm_total_tons'=>'تۆنی تۆمارکراو','adm_total_msgs'=>'نامە',
  'adm_moderate'=>'چاودێری','adm_set_role'=>'ڕۆڵ بگۆڕە','adm_owner'=>'خاوەن','adm_self'=>'تۆ',
  'prof_title'=>'پرۆفایلی من','prof_eyebrow'=>'هەژمارەکەت','prof_public'=>'پرۆفایلی ئەندام',
  'prof_details'=>'وردەکاری پرۆفایل','prof_name'=>'ناوی تەواو','prof_email'=>'ئیمەیل',
  'prof_email_fixed'=>'ئیمەیل چوونەژوورەوەی تۆیە و لێرە ناگۆڕدرێت.',
  'prof_industry'=>'پیشەسازی','prof_farm_type'=>'جۆری کێڵگە','prof_preferred'=>'ماددەی پەسەندکراو',
  'prof_main_material'=>'ماددەی سەرەکی','prof_preferred_hint'=>'لیستەکەت ٦٥ خاڵ بەم ماددەیە دەدات لە جیاتی ١٥.',
  'prof_district'=>'ناوچە','prof_district_pick'=>'ناوچەیەک هەڵبژێرە بۆ پڕکردنی پێوەرەکان…',
  'prof_coord_buyer'=>'ئەم پێوەرەکان شوێنی کارگەی تۆیە. نزیکی و ڕێگەی کۆکردنەوە لێرەوە دەپێورێت.',
  'prof_coord_farmer'=>'ئەم پێوەرەکان شوێنی وەرگرتنی بنەڕەتی بۆ تۆمارەکانی نوێیە.',
  'prof_save'=>'پرۆفایل پاشەکەوت بکە','prof_password'=>'وشەی تێپەر','prof_current'=>'وشەی تێپەری ئێستا',
  'prof_new'=>'وشەی تێپەری نوێ','prof_new_hint'=>'بەلایەنی کەم ١٠ پیت.','prof_change'=>'وشەی تێپەر بگۆڕە',
  'prof_account'=>'هەژمار','prof_role_fixed'=>'تەنها بەڕێوەبەر دەتوانێت ڕۆڵەکەت بگۆڕێت.',
  'prof_message'=>'نامە بنێرە','prof_view_public'=>'پرۆفایلی گشتی ببینە','prof_region'=>'ناوچە',
  'prof_my_lots'=>'بڕەکانی بەردەستی من','prof_their_lots'=>'بڕەکانی بەردەست','prof_no_lots'=>'ئێستا هیچ بڕێک بەردەست نییە.',
  'prof_missing'=>'ئەو پرۆفایلە بوونی نییە.','nav_profile'=>'پرۆفایلی من',
 ],
 'ar'=>[
  'nav_market'=>'السوق','nav_matches'=>'المطابقات الذكية','nav_inventory'=>'مخزوني','nav_quick'=>'إدراج سريع',
  'nav_pool'=>'تجميع الكميات','nav_map'=>'خريطة الاستلام','nav_chat'=>'الرسائل','nav_knowledge'=>'معلومات المواد','nav_admin'=>'الإدارة',
  'signin'=>'تسجيل الدخول / انضم','signout'=>'تسجيل الخروج','workspace'=>'مساحة العمل','account'=>'حساب',
  'quick_eyebrow'=>'تحدث أو اكتب — بدون نماذج','quick_title'=>'فقط أخبرنا بما لديك.',
  'quick_lead'=>'اوصف مادتك بكلماتك. سنعبئ الإدراج لتتحقق منه.',
  'quick_placeholder'=>'مثال: لدي حوالي ٣ أطنان من قشور الرمان المجففة في سيد صادق، مفروزة وجاهزة الأسبوع القادم.',
  'quick_read'=>'اقرأ وصفي','quick_speak'=>'تحدث بدلاً من ذلك','quick_listening'=>'أستمع… تحدث الآن.',
  'quick_review'=>'تحقق من هذه التفاصيل','quick_review_hint'=>'عبأناها من وصفك. صحح أي خطأ ثم احفظ.',
  'quick_confirm'=>'احفظ الإدراج','quick_missing'=>'لم نتمكن من قراءة كل شيء. أكمل الحقول المحددة.',
  'material'=>'المادة','quantity'=>'الكمية (طن)','price'=>'السعر / طن (دينار)','location'=>'الموقع',
  'latitude'=>'خط العرض','longitude'=>'خط الطول','notes'=>'التحضير / الجودة','status'=>'الحالة',
  'actions'=>'إجراءات','farmer'=>'مزارع','buyer'=>'مشتري','all'=>'الكل','none_yet'=>'لا يوجد شيء هنا بعد.',
  'pool_eyebrow'=>'شاحنة واحدة. عدة مزارع.','pool_title'=>'اجمع الكميات الصغيرة في عملية استلام واحدة.',
  'pool_lead'=>'لا مزرعة واحدة تملك عشرين طناً. معاً تملكها. اجمع الكميات القريبة من نفس المادة.',
  'pool_target'=>'الكمية المطلوبة','pool_radius'=>'نطاق البحث (كم)','pool_build'=>'أنشئ كمية مجمعة',
  'pool_total'=>'الحجم المجمع','pool_farms'=>'المزارع المشاركة','pool_point'=>'نقطة الجمع المقترحة',
  'pool_route'=>'خطط مسار الجمع','pool_none'=>'لا توجد كميات من هذه المادة في هذا النطاق بعد.',
  'pool_short'=>'الكميات المتاحة لم تبلغ هدفك بعد. هذا كل ما هو في النطاق.',
  'burn_title'=>'إذا تم حرقها بدلاً من ذلك','burn_revenue'=>'الدخل الذي يخسره المزارع',
  'burn_soil'=>'قاست دراسة من عام ٢٠٢٥ لحرق مخلفات الحنطة في قرية وەژە وسيتك، السليمانية، انخفاض المادة العضوية في التربة بنحو ٢٥٪ والمغنيسيوم بنحو الثلثين.',
  'sup_eyebrow'=>'مساحة عمل المورد','sup_title'=>'حصادك يمكن أن يعطي أكثر.',
  'sup_lead'=>'أدر كل كمية، حدّث التوفر، وانظر من يسأل من المشترين.',
  'sup_lots'=>'الكميات المدرجة','sup_available'=>'متاح الآن','sup_reserved'=>'محجوز','sup_sold'=>'مبيع',
  'sup_value'=>'قيمة المخزون','sup_interest'=>'مشترون مهتمون','sup_inventory'=>'مخزون المواد',
  'sup_add'=>'أضف مادة','sup_edit'=>'عدّل المادة','sup_new'=>'إدراج جديد','sup_save'=>'احفظ المخزون',
  'sup_delete'=>'أزل الإدراج','sup_buyers'=>'مشترون تابعوك','sup_no_buyers'=>'لم يتابعك أي مشتر بعد. أبقِ كمياتك متاحة.',
  'sup_score'=>'الملاءمة','sup_search'=>'ابحث في كمياتك','sup_locate'=>'استخدم موقعي','sup_photo'=>'صورة المخزون',
  'buy_eyebrow'=>'مساحة عمل المشتري','buy_title'=>'موارد محلية. مطابقات أفضل.',
  'buy_lead'=>'قائمتك المرتبة، المزارعون الذين تتابعهم، وملخص الشراء.',
  'buy_matched'=>'كميات مطابقة','buy_reachable'=>'أطنان في المتناول','buy_following'=>'مزارعون متابَعون',
  'buy_avg'=>'متوسط الملاءمة','buy_shortlist'=>'قائمة موادك','buy_follow_list'=>'المزارعون الذين تتابعهم',
  'buy_unfollow'=>'أزل من القائمة','buy_no_following'=>'لا تتابع أي مزارع بعد. تابع واحداً من قائمتك.',
  'buy_brief'=>'ملخص الشراء','buy_generate'=>'أنشئ ملخص AI','buy_open_pool'=>'اجمع الكميات في استلام واحد',
  'adm_eyebrow'=>'الإدارة','adm_title'=>'الإشراف على المنصة.',
  'adm_lead'=>'الحسابات، الإشراف على الإدراجات، وإجماليات المنصة. هذه وحدة تحكم تجريبية.',
  'adm_users'=>'الحسابات','adm_listings'=>'كل الإدراجات','adm_role'=>'الدور','adm_joined'=>'انضم',
  'adm_total_users'=>'حسابات','adm_total_lots'=>'إدراجات','adm_total_tons'=>'أطنان مدرجة','adm_total_msgs'=>'رسائل',
  'adm_moderate'=>'إشراف','adm_set_role'=>'غيّر الدور','adm_owner'=>'المالك','adm_self'=>'أنت',
  'prof_title'=>'ملفي','prof_eyebrow'=>'حسابك','prof_public'=>'ملف العضو',
  'prof_details'=>'تفاصيل الملف','prof_name'=>'الاسم الكامل','prof_email'=>'البريد الإلكتروني',
  'prof_email_fixed'=>'البريد هو معرّف دخولك ولا يمكن تغييره هنا.',
  'prof_industry'=>'الصناعة','prof_farm_type'=>'نوع المزرعة','prof_preferred'=>'المادة المفضلة',
  'prof_main_material'=>'المادة الرئيسية','prof_preferred_hint'=>'قائمتك تمنح هذه المادة ٦٥ نقطة بدلاً من ١٥.',
  'prof_district'=>'القضاء','prof_district_pick'=>'اختر قضاءً لتعبئة الإحداثيات…',
  'prof_coord_buyer'=>'هذه إحداثيات منشأتك. يُقاس القرب ومسارات الجمع من هنا.',
  'prof_coord_farmer'=>'هذه نقطة الاستلام الافتراضية لإدراجاتك الجديدة.',
  'prof_save'=>'احفظ الملف','prof_password'=>'كلمة المرور','prof_current'=>'كلمة المرور الحالية',
  'prof_new'=>'كلمة مرور جديدة','prof_new_hint'=>'١٠ أحرف على الأقل.','prof_change'=>'غيّر كلمة المرور',
  'prof_account'=>'الحساب','prof_role_fixed'=>'المدير فقط يمكنه تغيير دورك.',
  'prof_message'=>'أرسل رسالة','prof_view_public'=>'اعرض الملف العام','prof_region'=>'المنطقة',
  'prof_my_lots'=>'كمياتي المتاحة','prof_their_lots'=>'الكميات المتاحة','prof_no_lots'=>'لا توجد كميات متاحة حالياً.',
  'prof_missing'=>'هذا الملف غير موجود.','nav_profile'=>'ملفي',
 ],
];
