<?php
require_once __DIR__.'/bootstrap.php';
function page_start(string $active,string $title): void { $u=user(); ?>
<!doctype html><html lang="<?=esc(lang()==='ckb'?'ckb':lang())?>" dir="<?=rtl()?'rtl':'ltr'?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="<?=esc($_SESSION['csrf'])?>"><title><?=esc($title)?> | EcoZîn</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" onerror="this.onerror=null;this.href='assets/bootstrap.min.css'"><link href="assets/leaflet.css" rel="stylesheet"><link href="assets/app.css" rel="stylesheet">
<script src="assets/jquery.min.js"></script><script src="assets/lucide.min.js"></script></head><body>
<aside class="sidebar"><a class="brand" href="index.php"><span class="brand-icon"><i data-lucide="sprout"></i></span>EcoZîn<span class="brand-dot">.</span></a><div class="workspace-label">CIRCULAR ECONOMY PLATFORM</div>
<nav><?php foreach(['index.php'=>['nav_market','store'],'business_dashboard.php'=>['nav_matches','sparkles'],'farmer_dashboard.php'=>['nav_inventory','package'],'voice_listing.php'=>['nav_quick','mic'],'pooling.php'=>['nav_pool','layers'],'map.php'=>['nav_map','map'],'chat.php'=>['nav_chat','message-circle'],'ai_knowledge_base.php'=>['nav_knowledge','flask-conical']] as $url=>$item): ?><a class="<?= $active===$url?'active':'' ?>" href="<?=$url?>"><i data-lucide="<?=$item[1]?>"></i><?=esc(t($item[0]))?></a><?php endforeach ?></nav>
<div class="sidebar-bottom"><div class="region"><span class="live-dot"></span> Slemani, Kurdistan Region</div><small>Smart Suli / Community pilot</small><hr><?php if($u): ?><strong><?=esc($u['full_name'])?></strong><div class="muted"><?=esc(ucfirst($u['role']))?> account</div><form action="auth.php" method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><button class="signout" name="action" value="logout">Sign out</button></form><?php else: ?><a href="index.php?view=login" class="btn btn-dark w-100">Sign in / Join</a><?php endif ?></div></aside>
<main><header class="topbar"><div><span class="muted">Workspace</span><span class="top-separator">/</span><?=esc($title)?></div><div class="top-actions"><span class="lang-switch"><?php foreach(['en'=>'EN','ckb'=>'کوردی','ar'=>'عربي'] as $code=>$label): ?><a class="<?=lang()===$code?'on':''?>" href="?lang=<?=$code?>" hreflang="<?=$code?>"><?=$label?></a><?php endforeach ?></span><span class="pilot-badge">DEMO DATA</span><?php if($u): ?><span class="avatar" title="<?=esc($u['full_name'])?>"><?=esc(strtoupper(substr($u['full_name'],0,2)))?></span><form action="auth.php" method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><button class="icon-btn" name="action" value="logout" title="Sign out" aria-label="Sign out"><i data-lucide="log-out"></i></button></form><?php else: ?><a class="icon-btn" href="index.php?view=login" title="Sign in / Join" aria-label="Sign in or join"><i data-lucide="log-in"></i></a><?php endif ?></div></header><div class="page-content"><div id="notice" role="status" hidden></div>
<?php }
function page_end(): void { ?><footer>EcoZîn <span>Made for a more circular Kurdistan.</span><span>Smart Suli 2026</span></footer></div></main><script src="assets/bootstrap.bundle.min.js"></script><script src="assets/app.js"></script></body></html><?php }
function listing_card(array $l,?array $match=null): void {
 $images=['Pomegranate'=>'pomegranate.jpg','Walnut'=>'walnut.jpg','Olive Pomace'=>'olive.jpg']; $names=['Pomegranate'=>'Pomegranate peels','Walnut'=>'Walnut shells','Olive Pomace'=>'Olive pomace / jift']; ?>
<article class="listing"><div class="listing-photo" style="background-image:url('<?=!empty($l['photo_url'])?'listing_photo.php?id='.(int)$l['id']:'assets/'.$images[$l['product_type']]?>')"><span class="material-tag"><?=esc($l['product_type'])?></span><span class="availability <?=esc($l['status'])?>"><?=esc(ucfirst($l['status']))?></span><?php if(empty($l['photo_url'])): ?><span class="reference-photo">Representative crop photo</span><?php endif ?></div><div class="listing-body"><div class="listing-kicker">AGRICULTURAL BYPRODUCT</div><h3><?=esc($names[$l['product_type']])?></h3><div class="farmer-line"><i data-lucide="user-round"></i><?=esc($l['full_name'])?><span> · Slemani region</span></div><p class="description"><?=esc($l['description'])?></p><div class="listing-numbers"><div><strong><?=number_format((float)$l['quantity_tons'],1)?><small> tons</small></strong><span>Available volume</span></div><div><strong><?=number_format((float)$l['price_per_ton'])?><small> IQD</small></strong><span>per ton / negotiable</span></div></div><?php if($match): ?><div class="match-reason"><i data-lucide="sparkles"></i><div><b><?=$match['score']?>% suitability</b><small><?=esc($match['reason'])?></small></div></div><?php endif ?><?php $forgone=(float)$l['quantity_tons']*(float)$l['price_per_ton']; if($forgone>0): ?><details class="burn-card"><summary><i data-lucide="flame"></i><?=esc(t('burn_title'))?></summary><div><b><?=esc(t('burn_revenue'))?>: <?=number_format($forgone)?> IQD</b><p><?=esc(t('burn_soil'))?></p><small>Soil figures from a published 2025 study of wheat residue in Sulaymaniyah Province. No emission or carbon-saving figure is claimed here.</small></div></details><?php endif ?><div class="listing-footer"><a href="map.php?listing=<?=$l['id']?>"><i data-lucide="map-pin"></i>Pickup location</a><?php if(user() && user()['role']==='business'): ?><button class="btn btn-sm btn-green follow" data-id="<?=$l['id']?>" <?= $l['status']!=='available'?'disabled':'' ?>>Follow farmer <i data-lucide="arrow-up-right"></i></button><?php else: ?><a class="btn btn-sm btn-light" href="index.php?view=login">Contact farmer <i data-lucide="arrow-up-right"></i></a><?php endif ?></div></div></article>
<?php }
