const {chromium}=require('C:/Users/khalc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');const base='http://localhost/echozhin/';
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 await page.goto(base+'index.php?view=login');const f=page.locator('form').filter({has:page.locator('input[value="register"]')});
 await f.locator('[name=full_name]').fill('Automation farmer');await f.locator('[name=email]').fill('automation-'+Date.now()+'@ecozin.test');await f.locator('[name=password]').fill('AutomationDemo2026!');await f.locator('[name=role]').selectOption('farmer');await f.locator('button').click();await page.waitForURL('**/farmer_dashboard.php');
 const inv=page.locator('#listing-form');await inv.locator('[name=quantity_tons]').fill('1.75');await inv.locator('[name=price_per_ton]').fill('45000');await inv.locator('[name=description]').fill('Automation sample <script>alert(1)</script>');await inv.locator('[name=photo]').setInputFiles('assets/pomegranate.jpg');await inv.locator('button').last().click();await page.waitForLoadState('networkidle');
 assert.ok((await page.locator('tbody').innerText()).includes('1.750'));assert.equal(await page.locator('tbody script').count(),0);
 await page.locator('.edit-listing').first().click();await inv.locator('[name=quantity_tons]').fill('2.25');await inv.locator('button').last().click();await page.waitForFunction(()=>document.querySelector('tbody').innerText.includes('2.250'));assert.ok((await page.locator('tbody').innerText()).includes('2.250'));
 await page.screenshot({path:'tests/artifacts/inventory.png',fullPage:true});
 const ownership=await page.evaluate(async()=>{const data=new FormData(document.getElementById('listing-form'));data.set('csrf',document.querySelector('meta[name=csrf-token]').content);data.set('id','1');data.set('quantity_tons','2');const r=await fetch('api_handler.php',{method:'POST',body:data});return r.status;});assert.equal(ownership,403);
 const rows=await (await page.request.get(base+'api_handler.php?action=listings')).json();const l=rows.listings.find(x=>x.description.startsWith('Automation sample'));assert.ok(l.photo_url);assert.equal((await page.request.get(base+'listing_photo.php?id='+l.id)).status(),200);assert.equal((await page.request.get(base+l.photo_url)).status(),403);
 const buyer=await browser.newPage();await buyer.goto(base+'index.php?view=login');const login=buyer.locator('form').filter({has:buyer.locator('input[value="login"]')});await login.locator('[name=email]').fill('buyer@ecozin.test');await login.locator('[name=password]').fill('EcozinDemo2026!');await login.locator('button').click();await buyer.waitForURL('**/business_dashboard.php');await buyer.locator('#recommendations').click();await buyer.waitForFunction(()=>document.getElementById('recommendation-source').textContent.includes('Local'));assert.ok((await buyer.locator('#recommendation-text').innerText()).includes('listing #'));
 const csrf=await buyer.locator('meta[name=csrf-token]').getAttribute('content');const forbidden=await buyer.request.post(base+'api_handler.php',{form:{action:'save_listing',csrf,product_type:'Walnut',quantity_tons:'3',price_per_ton:'1',location_lat:'35',location_lng:'45'}});assert.equal(forbidden.status(),403);
 await buyer.goto(base+'chat.php?receiver=1');await buyer.locator('#attachment').setInputFiles('assets/pomegranate.jpg');await buyer.locator('#message-text').fill('Automation attachment');await buyer.locator('.composer button').last().click();await buyer.waitForTimeout(600);const messages=await (await buyer.request.get(base+'api_handler.php?action=messages&receiver=1')).json();const m=messages.messages.find(x=>x.message_text==='Automation attachment');assert.ok(m.media_url);assert.equal((await buyer.request.get(base+'media.php?id='+m.id)).status(),200);assert.equal((await page.request.get(base+'media.php?id='+m.id)).status(),404);assert.equal((await buyer.request.get(base+m.media_url)).status(),403);
 await buyer.setViewportSize({width:390,height:844});await buyer.screenshot({path:'tests/artifacts/chat-mobile.png',fullPage:true});assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await buyer.goto(base+'map.php');await buyer.locator('#calculate-route').click();await buyer.waitForFunction(()=>!document.getElementById('calculate-route').disabled,{},{timeout:20000});console.log('Route service result:',await buyer.locator('#route-result').innerText());
 console.log('PASS: registration, farmer create/edit/photo, XSS escaping, ownership, buyer role, AI recommendation fallback, media authorization and mobile chat.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
